// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Box(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vals", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CallMethod(NIntegrate.Utilities.Reflection.ILExpression,System.Reflection.MethodInfo,NIntegrate.Utilities.Reflection.ILExpression[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vals", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CallStaticMethod(System.Reflection.MethodInfo,NIntegrate.Utilities.Reflection.ILExpression[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "str", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CallStringConcat(NIntegrate.Utilities.Reflection.ILExpression,NIntegrate.Utilities.Reflection.ILExpression,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vals", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CallStringFormat(NIntegrate.Utilities.Reflection.ILExpression,NIntegrate.Utilities.Reflection.ILExpression[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CallToString(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#ConvertAddress(NIntegrate.Utilities.Reflection.ILExpression,System.Type,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#ConvertValue(NIntegrate.Utilities.Reflection.ILExpression,System.Type,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "2#", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CreateConstructorCodeGenerator(System.Reflection.ConstructorInfo,System.Reflection.Emit.TypeBuilder,System.Reflection.Emit.ConstructorBuilder&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CreateConstructorCodeGenerator(System.Reflection.ConstructorInfo,System.Reflection.Emit.TypeBuilder,System.Reflection.Emit.ConstructorBuilder&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "2#", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CreateDefaultConstructorCodeGenerator(System.Reflection.ConstructorInfo,System.Reflection.Emit.TypeBuilder,System.Reflection.Emit.ConstructorBuilder&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CreateDefaultConstructorCodeGenerator(System.Reflection.ConstructorInfo,System.Reflection.Emit.TypeBuilder,System.Reflection.Emit.ConstructorBuilder&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "2#", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CreateDynamicMethodCodeGenerator(System.String,System.Type,System.Reflection.Emit.DynamicMethod&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1021:AvoidOutParameters", MessageId = "2#", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#CreateMethodCodeGenerator(System.Reflection.MethodInfo,System.Reflection.Emit.TypeBuilder,System.Reflection.Emit.MethodBuilder&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#ElseIf(NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#If(NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#IfNot(NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#InitializeValueTypeObject(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "bool", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "double", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "int", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "long", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Int64)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Single)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "float", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.Single)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "str", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Load(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Negate(NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "vals", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#New(System.Reflection.ConstructorInfo,NIntegrate.Utilities.Reflection.ILExpression[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Not(NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreArgument(System.Int32,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreArrayElement(NIntegrate.Utilities.Reflection.ILExpression,System.Type,System.Int32,NIntegrate.Utilities.Reflection.ILExpression,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreField(NIntegrate.Utilities.Reflection.ILExpression,System.Reflection.FieldInfo,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreLocalVariable(System.Int32,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreProperty(NIntegrate.Utilities.Reflection.ILExpression,System.Reflection.PropertyInfo,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreStaticField(System.Reflection.FieldInfo,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreStaticProperty(System.Reflection.PropertyInfo,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Unbox", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Unbox(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#Unbox(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Unbox", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#UnboxAny(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#UnboxAny(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "val", Scope = "member", Target = "NIntegrate.Utilities.Reflection.ILCodeGenerator.#StoreValueTypeObjectToStack(System.Type,NIntegrate.Utilities.Reflection.ILExpression)")]
