// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "NIntegrate.ServiceModel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "NIntegrate.ServiceModel.Activation")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "NIntegrate.ServiceModel.Collections.Generic")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2240:ImplementISerializableCorrectly", Scope = "type", Target = "NIntegrate.ServiceModel.ChannelFactoryCreationException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "NIntegrate.ServiceModel.ChannelFactoryCreationException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "NIntegrate.ServiceModel.ChannelFactoryFactory.#CreateChannelFactory`1(NIntegrate.ServiceModel.Configuration.WcfClientEndpoint,System.Uri[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "NIntegrate.ServiceModel.ChannelFactoryFactory.#CreateChannelFactory`1(NIntegrate.ServiceModel.Configuration.WcfClientEndpoint,System.Uri[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "NIntegrate.ServiceModel.ChannelFactoryFactory.#CreateChannelFactory`1(NIntegrate.ServiceModel.Configuration.WcfClientEndpoint,System.Uri[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "NIntegrate.ServiceModel.Activation.ServiceHostCreationException.#.ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "NIntegrate.ServiceModel.Activation.ServiceHostCreationException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "1#", Scope = "member", Target = "NIntegrate.ServiceModel.Activation.WcfServiceHostFactory.#CreateServiceHost(System.Type,System.Uri[]&,System.Object,NIntegrate.ServiceModel.Configuration.WcfService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorExtensionRegistry.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorExtensionRegistry.#AddItem(System.String,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorExtensionRegistry.#Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorExtensionRegistry.#Item[System.String]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorXml.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorXml.#FilterCustomBehaviorElements(System.Xml.XmlDocument)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1059:MembersShouldNotExposeCertainConcreteTypes", MessageId = "System.Xml.XmlNode", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BehaviorXml.#FilterCustomBehaviorElements(System.Xml.XmlDocument)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingElementExtensionRegistry.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingElementExtensionRegistry.#AddItem(System.String,System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingElementExtensionRegistry.#Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingElementExtensionRegistry.#Item[System.String]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingTypeDescription.#AvailableProtocols")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingTypeRegistry.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingTypeRegistry.#AddItem(System.String,NIntegrate.ServiceModel.Configuration.BindingTypeDescription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingTypeRegistry.#AddItem(System.String,NIntegrate.ServiceModel.Configuration.BindingTypeDescription)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2104:DoNotDeclareReadOnlyMutableReferenceTypes", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingTypeRegistry.#Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingTypeRegistry.#Item[System.String]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingXml.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.BindingXml.#FilterCustomBindingElementExtensionElements(System.Xml.XmlDocument)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.IdentityXml.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.WcfService.#Endpoints")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.WcfServiceEndpoint.#ListenUri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.ConfigurationXml.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.AppConfigLoader.#EnsureExtensionsLoaded()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.AppConfigLoader.#LoadClientEndpoint(System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.AppConfigLoader.#LoadService(System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "NIntegrate.ServiceModel.Configuration.AppConfigLoader.#LoadService(System.Type)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011:ConsiderPassingBaseTypesAsParameters", Scope = "member", Target = "NIntegrate.ServiceModel.WcfChannelFactoryFactory.#CreateChannelFactory`1(NIntegrate.ServiceModel.Configuration.WcfClientEndpoint,System.Uri[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1004:GenericMethodsShouldProvideTypeParameter", Scope = "member", Target = "NIntegrate.ServiceModel.WcfChannelFactoryFactory.#CreateChannelFactory`1(NIntegrate.ServiceModel.Configuration.WcfClientEndpoint,System.Uri[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "NIntegrate.ServiceModel.WcfChannelFactoryFactory.#CreateChannelFactory`1(NIntegrate.ServiceModel.Configuration.WcfClientEndpoint,System.Uri[])")]
