<?xml version="1.0" encoding="utf-8"?>
<Database Name="NIntegrateConfig" Class="StoredProceduresDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=NIntegrateConfig;Integrated Security=True" SettingsObjectName="NIntegrate.Properties.Settings" SettingsPropertyName="NIntegrateConfigConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_GetAllBindingTypes" Method="sp_GetAllBindingTypes">
    <ElementType Name="sp_GetAllBindingTypesResult">
      <Column Name="BindingType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BindingTypeFriendlyName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BindingTypeClassName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BindingConfigurationElementTypeClassName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChannelType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetConnectionString" Method="sp_GetConnectionString">
    <Parameter Name="ConnectionStringName" Parameter="connectionStringName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ServerName" Parameter="serverName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_GetConnectionStringResult">
      <Column Name="Value" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetAllCustomBehaviorTypes" Method="sp_GetAllCustomBehaviorTypes">
    <ElementType Name="sp_GetAllCustomBehaviorTypesResult">
      <Column Name="BehaviorType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BehaviorTypeExtensionName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BehaviorTypeFriendlyName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BehaviorTypeClassName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BehaviorConfigurationElementTypeClassName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BehaviorCategory_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetAllServiceHostTypes" Method="sp_GetAllServiceHostTypes">
    <ElementType Name="sp_GetAllServiceHostTypesResult">
      <Column Name="ServiceHostType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceHostTypeFriendlyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServiceHostTypeClassName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetAppVariable" Method="sp_GetAppVariable">
    <Parameter Name="AppVariableName" Parameter="appVariableName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AppCode" Parameter="appCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ServerName" Parameter="serverName" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_GetAppVariableResult">
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetClientConfiguration" Method="sp_GetClientConfiguration">
    <Parameter Name="ServiceContract" Parameter="serviceContract" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="ServerName" Parameter="serverName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AppCode" Parameter="appCode" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="sp_GetClientConfigurationResult">
      <Column Name="HostXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="EndpointAddress" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BindingNamespace" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EndpointBehaviorXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IdentityXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="BindingType_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BindingXML" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>