<%@ Page Title="Manage Applications" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeBehind="ManageApplications.aspx.cs" Inherits="NIntegrate.Configuration.UI.ManageApplications" MaintainScrollPositionOnPostback="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Manage Applications</h2>
    <div class="bottomhyperlink"><img alt="Add new application" src="Images/plus.gif" /><asp:LinkButton 
            ID="btnShowAddNewPanel" runat="server" Text="Add new application" 
            onclick="btnShowAddNewPanel_Click"></asp:LinkButton></div>
    <br />
    <asp:GridView CssClass="gridview"
        ID="gvApps" runat="server" 
        DataSourceID="dsApps"
        DataKeyNames="AppCode"
        AllowSorting="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false"
        AutoGenerateEditButton="true" onrowcommand="gvApps_RowCommand">
        <Columns>
            <asp:TemplateField HeaderText="AppCode" SortExpression="AppCode">
                <ItemTemplate>
                    <%#Eval("AppCode")%>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="tbAppCode" runat="server" MaxLength="10" Text='<%#Bind("AppCode") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator ID="tbAppCodeRequired" runat="server"
                        ControlToValidate="tbAppCode" EnableClientScript="false"
                        ErrorMessage="Required"></asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Name" SortExpression="Name">
                <ItemTemplate>
                    <%#Eval("Name") %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="tbName" runat="server" MaxLength="100" Text='<%#Bind("Name") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator ID="tbNameRequired" runat="server"
                        ControlToValidate="tbName" EnableClientScript="false"
                        ErrorMessage="Required"></asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:BoundField HeaderText="Description" DataField="Description" SortExpression="Description" />
            <asp:TemplateField HeaderText="AppVariables">
                <ItemTemplate>
                    <asp:LinkButton ID="btnViewAppVariables" runat="server" Text="Manage AppVariables" CommandName="Select" CommandArgument='<%# "ViewAppVariables|" + Eval("AppCode") %>'></asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <SelectedRowStyle BackColor="LightYellow" />
    </asp:GridView>
    <asp:Panel ID="panelBottom" runat="server" CssClass="panelBottom">
        <asp:DetailsView ID="dvAddApp" runat="server" Visible="false"
            DataSourceID="dsApps" DefaultMode="Insert"
            AutoGenerateRows="false"
            AutoGenerateInsertButton="true"
            CssClass="detailstable" onitemcommand="dvAddApp_ItemCommand" 
            oniteminserted="dvAddApp_ItemInserted">
            <Fields>
                <asp:TemplateField HeaderText="AppCode">
                    <InsertItemTemplate>
                        <asp:TextBox ID="tbAppCode" runat="server" MaxLength="10" Text='<%#Bind("AppCode") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="tbAppCodeRequired" runat="server"
                            ControlToValidate="tbAppCode" EnableClientScript="false"
                            ErrorMessage="Required"></asp:RequiredFieldValidator>
                    </InsertItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Name">
                    <InsertItemTemplate>
                        <asp:TextBox ID="tbName" runat="server" MaxLength="100" Text='<%#Bind("Name") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="tbNameRequired" runat="server"
                            ControlToValidate="tbName" EnableClientScript="false"
                            ErrorMessage="Required"></asp:RequiredFieldValidator>
                    </InsertItemTemplate>
                </asp:TemplateField>
                <asp:BoundField HeaderText="Description" DataField="Description" SortExpression="Description" />
            </Fields>
        </asp:DetailsView>
        <asp:Panel ID="panelAppVariables" runat="server" Visible="false">
            <div class="bottomhyperlink"><img alt="Add new appvariable" src="Images/plus.gif" /><asp:LinkButton 
                    ID="btnShowSubAddNewPanel" runat="server" Text="Add new appvariable" 
                    onclick="btnShowSubAddNewPanel_Click"></asp:LinkButton></div>
            <br />
            <asp:GridView CssClass="gridview"
                ID="gvAppVariables" runat="server" 
                DataSourceID="dsAppVariables"
                DataKeyNames="AppCode,AppVariableName,Environment_id"
                AllowSorting="true"
                AutoGenerateDeleteButton="true"
                AutoGenerateColumns="false"
                EmptyDataText="No AppVariables for selected application"
                AutoGenerateEditButton="true" onrowcommand="gvAppVariables_RowCommand">
                <Columns>
                    <asp:TemplateField HeaderText="AppVariableName" SortExpression="AppVariableName">
                        <ItemTemplate>
                            <%#Eval("AppVariableName")%>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="tbAppVariableName" runat="server" Text='<%#Bind("AppVariableName") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="tbAppVariableNameRequired" runat="server"
                                ControlToValidate="tbAppVariableName" EnableClientScript="false"
                                ErrorMessage="Required"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Application">
                        <ItemTemplate>
                            <asp:DropDownList ID="ddlApps" runat="server" SelectedValue='<%# Bind("AppCode") %>' DataSourceID="dsApps" DataTextField="Name" DataValueField="AppCode" Enabled="false"></asp:DropDownList>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlApps" runat="server" SelectedValue='<%# Bind("AppCode") %>' DataSourceID="dsApps" DataTextField="Name" DataValueField="AppCode"></asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Environment" SortExpression="Environment_id">
                        <ItemTemplate>
                            <asp:DropDownList ID="ddlEnvironments" runat="server" SelectedValue='<%# Bind("Environment_id") %>' DataSourceID="dsEnvironments" DataTextField="Name" DataValueField="Environment_id" Enabled="false"></asp:DropDownList>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlEnvironments" runat="server" SelectedValue='<%# Bind("Environment_id") %>' DataSourceID="dsEnvironments" DataTextField="Name" DataValueField="Environment_id"></asp:DropDownList>
                        </EditItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Value" SortExpression="Value">
                        <ItemTemplate>
                            <%#Eval("Value")%>
                        </ItemTemplate>
                        <EditItemTemplate>
                            <asp:TextBox ID="tbValue" runat="server" Text='<%#Bind("Value") %>'></asp:TextBox>
                            <asp:RequiredFieldValidator ID="tbValueRequired" runat="server"
                                ControlToValidate="tbValue" EnableClientScript="false"
                                ErrorMessage="Required"></asp:RequiredFieldValidator>
                        </EditItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <asp:Panel ID="panelAddAppVariable" runat="server" CssClass="panelBottom" Visible="false">
                <asp:HiddenField ID="hidSelectedAppCode" runat="server" />
                <asp:DetailsView ID="dvAddAppVariable" runat="server"
                    DataSourceID="dsAppVariables" DefaultMode="Insert"
                    AutoGenerateRows="false"
                    AutoGenerateInsertButton="true"
                    CssClass="detailstable" onitemcommand="dvAddAppVariable_ItemCommand" 
                    oniteminserted="dvAddAppVariable_ItemInserted" 
                    ondatabound="dvAddAppVariable_DataBound">
                    <Fields>
                        <asp:TemplateField HeaderText="AppVariableName">
                            <InsertItemTemplate>
                                <asp:TextBox ID="tbAppVariableName" runat="server" Text='<%#Bind("AppVariableName") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="tbAppVariableNameRequired" runat="server"
                                    ControlToValidate="tbAppVariableName" EnableClientScript="false"
                                    ErrorMessage="Required"></asp:RequiredFieldValidator>
                            </InsertItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Application">
                            <InsertItemTemplate>
                                <asp:DropDownList ID="ddlApps" runat="server" SelectedValue='<%# Bind("AppCode") %>' DataSourceID="dsApps" DataTextField="Name" DataValueField="AppCode"></asp:DropDownList>
                            </InsertItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Environment">
                            <InsertItemTemplate>
                                <asp:DropDownList ID="ddlEnvironments" runat="server" SelectedValue='<%# Bind("Environment_id") %>' DataSourceID="dsEnvironments" DataTextField="Name" DataValueField="Environment_id"></asp:DropDownList>
                            </InsertItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Value">
                            <InsertItemTemplate>
                                <asp:TextBox ID="tbValue" runat="server" Text='<%#Bind("Value") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="tbValueRequired" runat="server"
                                    ControlToValidate="tbValue" EnableClientScript="false"
                                    ErrorMessage="Required"></asp:RequiredFieldValidator>
                            </InsertItemTemplate>
                        </asp:TemplateField>
                    </Fields>
                </asp:DetailsView>            
            </asp:Panel>
        </asp:Panel>
    </asp:Panel>
    <ni:QueryDataSource ID="dsApps" runat="server" UseLocalQueryService="true">
    </ni:QueryDataSource>
    <ni:QueryDataSource ID="dsEnvironments" runat="server" UseLocalQueryService="true">
    </ni:QueryDataSource>
    <ni:QueryDataSource ID="dsAppVariables" runat="server" UseLocalQueryService="true">
    </ni:QueryDataSource>
</asp:Content>
