using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.Runtime.Serialization;
using NIntegrate.Data.Configuration;
using System.Reflection;
using NIntegrate.Mapping;

namespace NIntegrate.Data
{
    [DataContract(Namespace = "http://nintegrate.com")]
    [KnownType("KnownTypes")]
    public sealed class ObjectId<TRecord, TQuery>
        where TRecord : ActiveRecord
        where TQuery : QueryTable, new()
    {
        [DataMember]
        private readonly Condition _condition;
        [DataMember]
        private readonly bool _autoGenerated;

        #region Properties

        public bool AutoGenerated
        {
            get { return _autoGenerated; }
        }

        #endregion

        #region KnownTypes

        static Type[] KnownTypes()
        {
            return KnownTypeRegistry.Instance.KnownTypes;
        }

        #endregion

        #region Public Methods

        public ObjectId(Condition condition, bool autoGenerated)
        {
            if (Equals(condition, null))
                throw new ArgumentNullException("condition");

            _condition = condition;
            _autoGenerated = autoGenerated;
        }

        public QueryCriteria ToCriteria()
        {
            var query = ActiveRecord<TRecord, TQuery>.Q;
            return new QueryCriteria(query.TableName, query.ConnectionStringName, query.ReadOnly, query.PredefinedColumns)
                .Where(_condition);
        }

        #endregion
    }

    [DataContract(Namespace = "http://nintegrate.com")]
    public abstract class ActiveRecord
    {
        [DataMember]
        protected bool _isNew = true;
        protected QueryCommandFactory _cmdFactory;
        protected static readonly MapperFactory _mapperFac = new MapperFactory();

        #region Constructors

        internal ActiveRecord() { }

        #endregion

        #region Public Methods

        public void Attach(QueryCommandFactory cmdFactory)
        {
            _cmdFactory = cmdFactory;
        }

        public bool IsNew()
        {
            return _isNew;
        }

        public bool IsAttached()
        {
            return _cmdFactory != null;
        }

        public abstract bool Save(params Assignment[] assignments);

        public abstract int Save(QueryCriteria criteria);

        public abstract bool Delete();

        public abstract int Delete(QueryCriteria criteria);

        public abstract int Count(QueryCriteria criteria);

        #endregion
    }

    [DataContract(Namespace = "http://nintegrate.com")]
    public abstract class ActiveRecord<TRecord, TQuery> : ActiveRecord
        where TRecord : ActiveRecord
        where TQuery : QueryTable, new()
    {
        public static readonly TQuery Q = new TQuery();
        private static readonly Mapper<IDataReader, TRecord> _mapperOne;
        private static readonly Mapper<IDataReader, List<TRecord>> _mapperMany;

        #region Constructors

        static ActiveRecord()
        {
            _mapperFac.ConfigureMapper<IDataReader, TRecord>(true, true, true, "Q");
            _mapperOne = _mapperFac.GetMapper<IDataReader, TRecord>();

            _mapperFac.ConfigureMapper<IDataReader, List<TRecord>>(true, true, true);
            _mapperMany = _mapperFac.GetMapper<IDataReader, List<TRecord>>();
        }

        #endregion

        #region Public Methods

        public bool IsReadOnly()
        {
            return Q.ReadOnly;
        }

        public abstract ObjectId<TRecord, TQuery> GetObjectId();
        public abstract Assignment[] GetSaveAssignments();

        public virtual Assignment[] GetInsertAssignments()
        {
            return GetSaveAssignments();
        }

        public virtual void SetAutoGeneratedIdValue(params object[] values)
        {
            //only to be implemented in child class for saveable AutoGenerated ID ActiveRecord
        }

        public sealed override int Save(QueryCriteria criteria)
        {
            if (criteria == null)
                throw new ArgumentNullException("criteria");

            if (criteria.QueryType != QueryType.Update || criteria.TableName != Q.TableName)
                throw new ArgumentException("criteria invalid");

            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            if (IsReadOnly())
                throw new InvalidOperationException("readonly");

            return ExecuteNonQuery(criteria);
        }

        public override bool Save(params Assignment[] assignments)
        {
            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            if (IsReadOnly())
                throw new InvalidOperationException("readonly");

            var objectId = GetObjectId();

            if (objectId == null)
                throw new InvalidOperationException("GetObjectId() is null");

            var criteria = objectId.ToCriteria();
            criteria.QueryType = (IsNew() ? QueryType.Insert : QueryType.Update);

            ResolveaSaveAssignments(criteria, assignments);

            var result = false;

            if (criteria.QueryType == QueryType.Insert && objectId.AutoGenerated)
            {
                var autoGeneratedId = ExecuteScalar(criteria);
                result = (autoGeneratedId != DBNull.Value && autoGeneratedId != null);

                if (result)
                    SetAutoGeneratedIdValue(autoGeneratedId);
            }
            else
            {
                result = ExecuteNonQuery(criteria) > 0;
            }

            if (result)
                _isNew = false;

            return result;
        }

        public sealed override bool Delete()
        {
            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            if (IsReadOnly())
                throw new InvalidOperationException("readonly");

            bool result = false;

            var objectId = GetObjectId();
            if (objectId == null)
                throw new InvalidOperationException("GetObjectId() is null");

            var criteria = objectId.ToCriteria();
            criteria.QueryType = QueryType.Delete;

            result = ExecuteNonQuery(criteria) > 0;

            if (result)
                _isNew = true;

            return result;
        }

        public override int Delete(QueryCriteria criteria)
        {
            if (criteria == null)
                throw new ArgumentNullException("criteria");

            if (criteria.QueryType != QueryType.Delete || criteria.TableName != Q.TableName)
                throw new ArgumentException("criteria invalid");

            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            if (IsReadOnly())
                throw new InvalidOperationException("readonly");

            return ExecuteNonQuery(criteria);
        }

        public TRecord FindOne(ObjectId<TRecord, TQuery> id)
        {
            if (id == null)
                throw new ArgumentNullException("id");

            var criteria = id.ToCriteria();
            criteria.QueryType = QueryType.Select;
            return FindOne(criteria);
        }

        public TRecord FindOne(QueryCriteria criteria)
        {
            if (criteria == null)
                throw new ArgumentNullException("criteria");

            if (criteria.TableName != Q.TableName
                || (criteria.QueryType != QueryType.Select && criteria.QueryType != QueryType.Sproc))
            {
                throw new ArgumentException("criteria invalid");
            }

            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            return ExecuteOne(criteria);
        }

        public ICollection<TRecord> FindMany(QueryCriteria criteria)
        {
            if (criteria == null)
                throw new ArgumentNullException("criteria");

            if (criteria.TableName != Q.TableName
                || (criteria.QueryType != QueryType.Select && criteria.QueryType != QueryType.Sproc))
            {
                throw new ArgumentException("criteria invalid");
            }

            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            return ExecuteMany(criteria);
        }

        public override int Count(QueryCriteria criteria)
        {
            if (criteria == null)
                throw new ArgumentNullException("criteria");

            if (criteria.TableName != Q.TableName
                || (criteria.QueryType != QueryType.Select && criteria.QueryType != QueryType.Sproc))
            {
                throw new ArgumentException("criteria invalid");
            }

            if (!IsAttached())
                throw new InvalidOperationException("not attached");

            return ExecuteCount(criteria);
        }

        #endregion

        #region Non-Public Methods

        private int ExecuteNonQuery(QueryCriteria criteria)
        {
            using (var cmd = _cmdFactory.CreateCommand(criteria, false))
            {
                using (var conn = cmd.Connection)
                {
                    conn.Open();
                    return cmd.ExecuteNonQuery();
                }
            }
        }

        private object ExecuteScalar(QueryCriteria criteria)
        {
            using (var cmd = _cmdFactory.CreateCommand(criteria, false, true))
            {
                using (var conn = cmd.Connection)
                {
                    conn.Open();
                    return cmd.ExecuteScalar();
                }
            }
        }

        private TRecord ExecuteOne(QueryCriteria criteria)
        {
            using (var cmd = _cmdFactory.CreateCommand(criteria, false))
            {
                using (var conn = cmd.Connection)
                {
                    conn.Open();
                    using (var rdr = cmd.ExecuteReader())
                    {
                        if (rdr.Read())
                        {
                            var one = _mapperOne(rdr);
                            one.Attach(_cmdFactory);
                            return one;
                        }
                    }
                }
            }

            return default(TRecord);
        }

        private ICollection<TRecord> ExecuteMany(QueryCriteria criteria)
        {
            using (var cmd = _cmdFactory.CreateCommand(criteria, false))
            {
                using (var conn = cmd.Connection)
                {
                    conn.Open();
                    using (var rdr = cmd.ExecuteReader())
                    {
                        var many = _mapperMany(rdr);
                        if (many != null)
                        {
                            foreach (var one in many)
                            {
                                one.Attach(_cmdFactory);
                            }
                        }
                        return many;
                    }
                }
            }
        }

        private int ExecuteCount(QueryCriteria criteria)
        {
            using (var cmd = _cmdFactory.CreateCommand(criteria, true))
            {
                using (var conn = cmd.Connection)
                {
                    conn.Open();

                    return Convert.ToInt32(cmd.ExecuteScalar());
                }
            }
        }

        private void ResolveaSaveAssignments(QueryCriteria criteria, Assignment[] assignments)
        {
            if (assignments != null && assignments.Length > 0)
                criteria.SetAssignments(assignments);
            else if (criteria.QueryType == QueryType.Insert)
                criteria.SetAssignments(GetInsertAssignments());
            else
                criteria.SetAssignments(GetSaveAssignments());
        }

        #endregion
    }
}
