//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAppointments.UI.ServiceAgents.AppointmentService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "AppointmentCollection", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes", ItemName = "Appointment")]
    public class AppointmentCollection : System.Collections.Generic.List<EAppointments.UI.ServiceAgents.AppointmentService.Appointment>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Appointment", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class Appointment : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int UBRNField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Patient PatientField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Referrer ReferrerField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Provider ProviderField;

        private EAppointments.UI.ServiceAgents.AppointmentService.ClinicType ClinicTypeField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Slot SlotField;

        private System.Nullable<System.DateTime> StartDateTimeField;

        private System.Nullable<System.DateTime> EndDateTimeField;

        private System.DateTime CreatedDateTimeField;

        private System.DateTime UpdatedDateTimeField;

        private System.Nullable<System.DateTime> CancellationDateTimeField;

        private System.Nullable<System.Guid> CancelledByField;

        private string CancellationReasonField;

        private EAppointments.UI.ServiceAgents.AppointmentService.AppointmentStatus StatusField;

        private string CommentsField;

        private System.Nullable<System.DateTime> ReminderDateField;

        private System.Nullable<System.Guid> WorkflowIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UBRN
        {
            get
            {
                return this.UBRNField;
            }
            set
            {
                this.UBRNField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public EAppointments.UI.ServiceAgents.AppointmentService.Patient Patient
        {
            get
            {
                return this.PatientField;
            }
            set
            {
                this.PatientField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public EAppointments.UI.ServiceAgents.AppointmentService.Referrer Referrer
        {
            get
            {
                return this.ReferrerField;
            }
            set
            {
                this.ReferrerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public EAppointments.UI.ServiceAgents.AppointmentService.Provider Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public EAppointments.UI.ServiceAgents.AppointmentService.ClinicType ClinicType
        {
            get
            {
                return this.ClinicTypeField;
            }
            set
            {
                this.ClinicTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public EAppointments.UI.ServiceAgents.AppointmentService.Slot Slot
        {
            get
            {
                return this.SlotField;
            }
            set
            {
                this.SlotField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public System.Nullable<System.DateTime> StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.CreatedDateTimeField;
            }
            set
            {
                this.CreatedDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public System.DateTime UpdatedDateTime
        {
            get
            {
                return this.UpdatedDateTimeField;
            }
            set
            {
                this.UpdatedDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public System.Nullable<System.DateTime> CancellationDateTime
        {
            get
            {
                return this.CancellationDateTimeField;
            }
            set
            {
                this.CancellationDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public System.Nullable<System.Guid> CancelledBy
        {
            get
            {
                return this.CancelledByField;
            }
            set
            {
                this.CancelledByField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public string CancellationReason
        {
            get
            {
                return this.CancellationReasonField;
            }
            set
            {
                this.CancellationReasonField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public EAppointments.UI.ServiceAgents.AppointmentService.AppointmentStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 14)]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 15)]
        public System.Nullable<System.DateTime> ReminderDate
        {
            get
            {
                return this.ReminderDateField;
            }
            set
            {
                this.ReminderDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 16)]
        public System.Nullable<System.Guid> WorkflowId
        {
            get
            {
                return this.WorkflowIdField;
            }
            set
            {
                this.WorkflowIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Patient", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private string PatientNoField;

        private string TitleField;

        private string FirstNameField;

        private string LastNameField;

        private char GenderField;

        private System.Nullable<System.DateTime> DateOfBirthField;

        private string AddressLine1Field;

        private string AddressLine2Field;

        private string CityField;

        private string StateField;

        private string CountryField;

        private string ZipCodeField;

        private string ContactNumberField;

        private string EmailField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Referrer ReferrerField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string PatientNo
        {
            get
            {
                return this.PatientNoField;
            }
            set
            {
                this.PatientNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public char Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 9)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 10)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 11)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 12)]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 13)]
        public string ContactNumber
        {
            get
            {
                return this.ContactNumberField;
            }
            set
            {
                this.ContactNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 14)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 15)]
        public EAppointments.UI.ServiceAgents.AppointmentService.Referrer Referrer
        {
            get
            {
                return this.ReferrerField;
            }
            set
            {
                this.ReferrerField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Referrer", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class Referrer : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private string FirstNameField;

        private string LastNameField;

        private string ClinicNameField;

        private string EmailField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string ClinicName
        {
            get
            {
                return this.ClinicNameField;
            }
            set
            {
                this.ClinicNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Provider", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class Provider : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private string NameField;

        private string LocationField;

        private string OrganizationField;

        private string EmailField;

        private double LatitudeField;

        private double LongitudeField;

        private string ConditionsTreatedField;

        private string ProceduresPerformedField;

        private string ExclusionsField;

        private string AlternativeServicesField;

        private double ProximityField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public string Organization
        {
            get
            {
                return this.OrganizationField;
            }
            set
            {
                this.OrganizationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public string ConditionsTreated
        {
            get
            {
                return this.ConditionsTreatedField;
            }
            set
            {
                this.ConditionsTreatedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public string ProceduresPerformed
        {
            get
            {
                return this.ProceduresPerformedField;
            }
            set
            {
                this.ProceduresPerformedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 9)]
        public string Exclusions
        {
            get
            {
                return this.ExclusionsField;
            }
            set
            {
                this.ExclusionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 10)]
        public string AlternativeServices
        {
            get
            {
                return this.AlternativeServicesField;
            }
            set
            {
                this.AlternativeServicesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public double Proximity
        {
            get
            {
                return this.ProximityField;
            }
            set
            {
                this.ProximityField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ClinicType", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class ClinicType : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Specialty SpecialtyField;

        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public EAppointments.UI.ServiceAgents.AppointmentService.Specialty Specialty
        {
            get
            {
                return this.SpecialtyField;
            }
            set
            {
                this.SpecialtyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Slot", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class Slot : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private EAppointments.UI.ServiceAgents.AppointmentService.Provider ProviderField;

        private EAppointments.UI.ServiceAgents.AppointmentService.ClinicType ClinicTypeField;

        private System.DateTime StartDateTimeField;

        private System.DateTime EndDateTimeField;

        private System.Nullable<int> UBRNField;

        private EAppointments.UI.ServiceAgents.AppointmentService.SlotStatus StatusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public EAppointments.UI.ServiceAgents.AppointmentService.Provider Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public EAppointments.UI.ServiceAgents.AppointmentService.ClinicType ClinicType
        {
            get
            {
                return this.ClinicTypeField;
            }
            set
            {
                this.ClinicTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public System.DateTime StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.DateTime EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.Nullable<int> UBRN
        {
            get
            {
                return this.UBRNField;
            }
            set
            {
                this.UBRNField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public EAppointments.UI.ServiceAgents.AppointmentService.SlotStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppointmentStatus", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public enum AppointmentStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Booked = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 8,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 16,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Elapsed = 32,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Specialty", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class Specialty : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid IdField;

        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SlotStatus", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public enum SlotStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Available = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Booked = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppointmentSearchCriteria", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.DataTypes")]
    public partial class AppointmentSearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Nullable<int> UbrnField;

        private System.Nullable<int> StatusField;

        private System.Nullable<System.Guid> PatientIdField;

        private System.Nullable<System.Guid> ReferrerIdField;

        private System.Nullable<System.Guid> ProviderIdField;

        private System.Nullable<System.DateTime> StartDateTimeField;

        private System.Nullable<System.DateTime> EndDateTimeField;

        private System.Nullable<System.DateTime> CreatedDateTimeField;

        private System.Nullable<System.Guid> WorkflowIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ubrn
        {
            get
            {
                return this.UbrnField;
            }
            set
            {
                this.UbrnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Nullable<int> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public System.Nullable<System.Guid> PatientId
        {
            get
            {
                return this.PatientIdField;
            }
            set
            {
                this.PatientIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public System.Nullable<System.Guid> ReferrerId
        {
            get
            {
                return this.ReferrerIdField;
            }
            set
            {
                this.ReferrerIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 4)]
        public System.Nullable<System.Guid> ProviderId
        {
            get
            {
                return this.ProviderIdField;
            }
            set
            {
                this.ProviderIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 5)]
        public System.Nullable<System.DateTime> StartDateTime
        {
            get
            {
                return this.StartDateTimeField;
            }
            set
            {
                this.StartDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 6)]
        public System.Nullable<System.DateTime> EndDateTime
        {
            get
            {
                return this.EndDateTimeField;
            }
            set
            {
                this.EndDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 7)]
        public System.Nullable<System.DateTime> CreatedDateTime
        {
            get
            {
                return this.CreatedDateTimeField;
            }
            set
            {
                this.CreatedDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 8)]
        public System.Nullable<System.Guid> WorkflowId
        {
            get
            {
                return this.WorkflowIdField;
            }
            set
            {
                this.WorkflowIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
    public partial class SystemFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MessageField;

        private System.Guid IdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
    public partial class AppointmentServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MessageField;

        private System.Guid IdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "ExpressionCollection", Namespace = "http://schemas.datacontract.org/2004/07/NIntegrate.Data", ItemName = "anyType")]
    public class ExpressionCollection : System.Collections.Generic.List<object>
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08", ConfigurationName = "EAppointments.UI.ServiceAgents.AppointmentService.IAppointmentService")]
    public interface IAppointmentService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "Query", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/QueryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/QuerySystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/QuerySecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/QueryAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.ServiceModel.CommunicationException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.Appointment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.Patient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.Referrer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.Provider))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.ClinicType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.Specialty))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.Slot))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SlotStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentSearchCriteria))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Assignment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Assignment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Condition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.BooleanExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Expression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ParameterEqualsCondition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.NullExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ByteExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int16Expression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int32Expression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int64Expression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DateTimeExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.StringExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.GuidExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DoubleExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DecimalExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.BinaryExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.ExpressionCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.BooleanParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.SprocParameterDirection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ByteParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int16ParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int32ParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int64ParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DateTimeParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.StringParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.GuidParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DoubleParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DecimalParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.BinaryParameterExpression))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.BooleanColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ByteColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int16Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int32Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Int64Column))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DateTimeColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.StringColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.GuidColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DoubleColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.DecimalColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.BinaryColumn))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.QueryTable))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.QuerySproc))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ConditionAndOr[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ConditionAndOr))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.Condition[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ExpressionOperator))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.QueryType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NIntegrate.Data.ParameterEqualsCondition[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.SystemException))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        EAppointments.UI.ServiceAgents.AppointmentService.AppointmentCollection Query(NIntegrate.Data.QueryCriteria criteria);

        [System.ServiceModel.OperationContractAttribute(Action = "Find", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/FindResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/FindSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/FindSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/FindAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        EAppointments.UI.ServiceAgents.AppointmentService.AppointmentCollection Find(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentSearchCriteria criteria);

        [System.ServiceModel.OperationContractAttribute(Action = "Save", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/SaveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/SaveSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/SaveAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/SaveSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        EAppointments.UI.ServiceAgents.AppointmentService.Appointment Save(EAppointments.UI.ServiceAgents.AppointmentService.Appointment appointment);

        [System.ServiceModel.OperationContractAttribute(Action = "Book", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/BookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/BookSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/BookAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/BookSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        void Book(int ubrn, System.Guid slotId);

        [System.ServiceModel.OperationContractAttribute(Action = "Cancel", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/CancelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/CancelSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/CancelAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/CancelSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        void Cancel(int ubrn, string cancellationReason);

        [System.ServiceModel.OperationContractAttribute(Action = "Rebook", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RebookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RebookAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RebookSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RebookSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        void Rebook(int ubrn, System.Guid slotId);

        [System.ServiceModel.OperationContractAttribute(Action = "Approve", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/ApproveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/ApproveSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/ApproveSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/ApproveAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        void Approve(int ubrn);

        [System.ServiceModel.OperationContractAttribute(Action = "Reject", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RejectResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RejectSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RejectAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/RejectSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        void Reject(int ubrn);

        [System.ServiceModel.OperationContractAttribute(Action = "Delete", ReplyAction = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/DeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.SystemFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/DeleteSystemFaultFault", Name = "SystemFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.Security.SecurityAccessDeniedException), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/DeleteSecurityAccessDeniedExceptionFault", Name = "SecurityAccessDeniedException", Namespace = "http://schemas.datacontract.org/2004/07/System.ServiceModel.Security")]
        [System.ServiceModel.FaultContractAttribute(typeof(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentServiceFault), Action = "http://EAppointments.BMS.ServiceContracts/Appointment/2007/08/IAppointmentService" +
            "/DeleteAppointmentServiceFaultFault", Name = "AppointmentServiceFault", Namespace = "http://schemas.datacontract.org/2004/07/EAppointments.BMS.ServiceContracts")]
        void Delete(int ubrn);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAppointmentServiceChannel : EAppointments.UI.ServiceAgents.AppointmentService.IAppointmentService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AppointmentServiceClient : System.ServiceModel.ClientBase<EAppointments.UI.ServiceAgents.AppointmentService.IAppointmentService>, EAppointments.UI.ServiceAgents.AppointmentService.IAppointmentService
    {

        public AppointmentServiceClient()
        {
        }

        public AppointmentServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public AppointmentServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public AppointmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public AppointmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public EAppointments.UI.ServiceAgents.AppointmentService.AppointmentCollection Query(NIntegrate.Data.QueryCriteria criteria)
        {
            return base.Channel.Query(criteria);
        }

        public EAppointments.UI.ServiceAgents.AppointmentService.AppointmentCollection Find(EAppointments.UI.ServiceAgents.AppointmentService.AppointmentSearchCriteria criteria)
        {
            return base.Channel.Find(criteria);
        }

        public EAppointments.UI.ServiceAgents.AppointmentService.Appointment Save(EAppointments.UI.ServiceAgents.AppointmentService.Appointment appointment)
        {
            return base.Channel.Save(appointment);
        }

        public void Book(int ubrn, System.Guid slotId)
        {
            base.Channel.Book(ubrn, slotId);
        }

        public void Cancel(int ubrn, string cancellationReason)
        {
            base.Channel.Cancel(ubrn, cancellationReason);
        }

        public void Rebook(int ubrn, System.Guid slotId)
        {
            base.Channel.Rebook(ubrn, slotId);
        }

        public void Approve(int ubrn)
        {
            base.Channel.Approve(ubrn);
        }

        public void Reject(int ubrn)
        {
            base.Channel.Reject(ubrn);
        }

        public void Delete(int ubrn)
        {
            base.Channel.Delete(ubrn);
        }
    }
}
