//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAppointments.UI.Modules.Query
{
    
    
    public partial class Appointment : NIntegrate.Data.QueryTable
    {
        
        private NIntegrate.Data.Int32Column _UBRN = new NIntegrate.Data.Int32Column("UBRN");
        
        private NIntegrate.Data.GuidColumn _PatientId = new NIntegrate.Data.GuidColumn("PatientId");
        
        private NIntegrate.Data.GuidColumn _ReferrerId = new NIntegrate.Data.GuidColumn("ReferrerId");
        
        private NIntegrate.Data.GuidColumn _ProviderId = new NIntegrate.Data.GuidColumn("ProviderId");
        
        private NIntegrate.Data.GuidColumn _SlotId = new NIntegrate.Data.GuidColumn("SlotId");
        
        private NIntegrate.Data.DateTimeColumn _CreatedDate = new NIntegrate.Data.DateTimeColumn("CreatedDate");
        
        private NIntegrate.Data.DateTimeColumn _StartDateTime = new NIntegrate.Data.DateTimeColumn("StartDateTime");
        
        private NIntegrate.Data.DateTimeColumn _EndDateTime = new NIntegrate.Data.DateTimeColumn("EndDateTime");
        
        private NIntegrate.Data.DateTimeColumn _UpdatedDate = new NIntegrate.Data.DateTimeColumn("UpdatedDate");
        
        private NIntegrate.Data.GuidColumn _CancelledBy = new NIntegrate.Data.GuidColumn("CancelledBy");
        
        private NIntegrate.Data.DateTimeColumn _CancelledDate = new NIntegrate.Data.DateTimeColumn("CancelledDate");
        
        private NIntegrate.Data.StringColumn _CancellationReason = new NIntegrate.Data.StringColumn("CancellationReason", true);
        
        private NIntegrate.Data.Int32Column _Status = new NIntegrate.Data.Int32Column("Status");
        
        private NIntegrate.Data.StringColumn _Comments = new NIntegrate.Data.StringColumn("Comments", true);
        
        private NIntegrate.Data.DateTimeColumn _ReminderDate = new NIntegrate.Data.DateTimeColumn("ReminderDate");
        
        private NIntegrate.Data.GuidColumn _WorkflowId = new NIntegrate.Data.GuidColumn("WorkflowId");
        
        private NIntegrate.Data.GuidColumn _ClinicTypeId = new NIntegrate.Data.GuidColumn("ClinicTypeId");
        
        public Appointment() :
            base("Appointment", "EAppointments", false)
        {
        }
        
        public NIntegrate.Data.Int32Column UBRN
        {
            get
            {
                return this._UBRN;
            }
        }
        
        public NIntegrate.Data.GuidColumn PatientId
        {
            get
            {
                return this._PatientId;
            }
        }
        
        public NIntegrate.Data.GuidColumn ReferrerId
        {
            get
            {
                return this._ReferrerId;
            }
        }
        
        public NIntegrate.Data.GuidColumn ProviderId
        {
            get
            {
                return this._ProviderId;
            }
        }
        
        public NIntegrate.Data.GuidColumn SlotId
        {
            get
            {
                return this._SlotId;
            }
        }
        
        public NIntegrate.Data.DateTimeColumn CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
        }
        
        public NIntegrate.Data.DateTimeColumn StartDateTime
        {
            get
            {
                return this._StartDateTime;
            }
        }
        
        public NIntegrate.Data.DateTimeColumn EndDateTime
        {
            get
            {
                return this._EndDateTime;
            }
        }
        
        public NIntegrate.Data.DateTimeColumn UpdatedDate
        {
            get
            {
                return this._UpdatedDate;
            }
        }
        
        public NIntegrate.Data.GuidColumn CancelledBy
        {
            get
            {
                return this._CancelledBy;
            }
        }
        
        public NIntegrate.Data.DateTimeColumn CancelledDate
        {
            get
            {
                return this._CancelledDate;
            }
        }
        
        public NIntegrate.Data.StringColumn CancellationReason
        {
            get
            {
                return this._CancellationReason;
            }
        }
        
        public NIntegrate.Data.Int32Column Status
        {
            get
            {
                return this._Status;
            }
        }
        
        public NIntegrate.Data.StringColumn Comments
        {
            get
            {
                return this._Comments;
            }
        }
        
        public NIntegrate.Data.DateTimeColumn ReminderDate
        {
            get
            {
                return this._ReminderDate;
            }
        }
        
        public NIntegrate.Data.GuidColumn WorkflowId
        {
            get
            {
                return this._WorkflowId;
            }
        }
        
        public NIntegrate.Data.GuidColumn ClinicTypeId
        {
            get
            {
                return this._ClinicTypeId;
            }
        }
    }
}
