<%@ Page Title="Manage ServiceContract Compatibilities" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeBehind="ManageServiceContractCompatibilities.aspx.cs" Inherits="NIntegrate.Configuration.UI.ManageServiceContractCompatibilities" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2>Manage ServiceContract Compatibilities</h2>
    <div class="bottomhyperlink"><img alt="Add new servicecontract compatibility" src="Images/plus.gif" /><asp:LinkButton 
            ID="btnShowAddNewPanel" runat="server" Text="Add new servicecontract compatibility" 
            onclick="btnShowAddNewPanel_Click"></asp:LinkButton></div>
    <br />
    <asp:GridView CssClass="gridview"
        ID="gvServiceContractCompatibilities" runat="server" 
        DataSourceID="dsServiceContractCompatibilities"
        DataKeyNames="ServiceContract, CompatibleServiceContract"
        AllowSorting="true"
        AutoGenerateDeleteButton="true"
        AutoGenerateColumns="false"
        AutoGenerateEditButton="true" onrowcommand="gvServiceContractCompatibilities_RowCommand">
        <Columns>
            <asp:TemplateField HeaderText="ServiceContract" SortExpression="ServiceContract">
                <ItemTemplate>
                    <%#Eval("ServiceContract")%>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="tbServiceContract" runat="server" MaxLength="255" Text='<%#Bind("ServiceContract") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator ID="tbServiceContractRequired" runat="server"
                        ControlToValidate="tbServiceContract" EnableClientScript="false"
                        ErrorMessage="Required"></asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>        
            <asp:TemplateField HeaderText="CompatibleServiceContract" SortExpression="CompatibleServiceContract">
                <ItemTemplate>
                    <%#Eval("CompatibleServiceContract")%>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="tbCompatibleServiceContract" runat="server" MaxLength="255" Text='<%#Bind("CompatibleServiceContract") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator ID="tbCompatibleServiceContractRequired" runat="server"
                        ControlToValidate="tbCompatibleServiceContract" EnableClientScript="false"
                        ErrorMessage="Required"></asp:RequiredFieldValidator>
                </EditItemTemplate>
            </asp:TemplateField>        
        </Columns>
        <SelectedRowStyle BackColor="LightYellow" />
    </asp:GridView>
    <asp:Panel ID="panelBottom" runat="server" CssClass="panelBottom">
        <asp:DetailsView ID="dvAddServiceContractCompatibility" runat="server" Visible="false"
            DataSourceID="dsServiceContractCompatibilities" DefaultMode="Insert"
            AutoGenerateRows="false"
            AutoGenerateInsertButton="true"
            CssClass="detailstable" onitemcommand="dvAddServiceContractCompatibility_ItemCommand" 
            oniteminserted="dvAddServiceContractCompatibility_ItemInserted">
            <Fields>
                <asp:TemplateField HeaderText="ServiceContract">
                    <InsertItemTemplate>
                        <asp:TextBox ID="tbServiceContract" runat="server" MaxLength="100" Text='<%#Bind("ServiceContract") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="tbServiceContractRequired" runat="server"
                            ControlToValidate="tbServiceContract" EnableClientScript="false"
                            ErrorMessage="Required"></asp:RequiredFieldValidator>
                    </InsertItemTemplate>
                </asp:TemplateField>            
                <asp:TemplateField HeaderText="CompatibleServiceContract">
                    <InsertItemTemplate>
                        <asp:TextBox ID="tbCompatibleServiceContract" runat="server" MaxLength="100" Text='<%#Bind("CompatibleServiceContract") %>'></asp:TextBox>
                        <asp:RequiredFieldValidator ID="tbCompatibleServiceContractRequired" runat="server"
                            ControlToValidate="tbCompatibleServiceContract" EnableClientScript="false"
                            ErrorMessage="Required"></asp:RequiredFieldValidator>
                    </InsertItemTemplate>
                </asp:TemplateField>            
            </Fields>
        </asp:DetailsView>
    </asp:Panel>
    <ni:QueryDataSource ID="dsServiceContractCompatibilities" runat="server" UseLocalQueryService="true">
    </ni:QueryDataSource>
</asp:Content>
